name: Bug report
description: Report a reproducible problem with SpecMaker
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Pre‑submission checks
      options:
        - label: I searched existing issues and discussions
          required: true
        - label: I can reproduce this with the latest `main`
          required: false
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Provide a minimal, self‑contained example if possible
      placeholder: |
        1. Steps
        2. to
        3. reproduce
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behavior and logs
      description: Paste error messages, stack traces, or logs
      render: text
  - type: input
    attributes:
      label: Python version
      placeholder: e.g., 3.10.14
  - type: input
    attributes:
      label: OS
      placeholder: e.g., macOS 14.6, Ubuntu 22.04, Windows 11


